export const connectDefaultWorks = '/getDefaultWorks'
export const connectPathUsers = '/getAllDataUsers'
export const connectPathInsertWorks = '/insertWorks'
export const connectPathUpdateWorks = '/updateWorks'
export const connectPathInsertRecordsManagement = '/insertRecordsManagement'
export const connectPathUpdateRecordsManagement = '/updateRecordsManagement'
export const connectPathDeleteRecordsManagement = '/deleteRecordsManagement'
export const connectPathIsUsedClientCost = '/isUsedClientCost'
export const connectPathInsertClientCost = '/insertClientCost'
export const connectPathUpdateClientCost = '/updateClientCost'
export const connectPathDeleteClientCost = '/deleteClientCost'
export const connectPathChangeYearRecordsManagement =
  '/changeYearRecordsManagement'
